### ISSUE TITLE
Contact existing organizations to understand existing research /concerns in this area

### ISSUE THREAD

**Issue by nikolajbaer** [BigDataForSanDiego/2019-Team-227#3]
Suggestions:

Reach out to
AARP
San Diego 211
https://ciesandiego.org/

We want to know if this map already exists, and what research is out there so we can augment it ,rather than redo it.

**Comment by awadomar1** [comment]
I'll get on this ASAP! Along with figuring out how the elderly are currently getting their transport needs met.
